/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as CreateEditorRouteImport } from './routes/create.editor'
import { Route as CreateMediaRouteImport } from './routes/create.media'
import { Route as OnboardingChannelsRouteImport } from './routes/onboarding.channels'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.role'
import { Route as OnboardingSourceRouteImport } from './routes/onboarding.source'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRoute,
} as any)
const CreateEditorRoute = CreateEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => CreateRoute,
} as any)
const CreateMediaRoute = CreateMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => CreateRoute,
} as any)
const OnboardingChannelsRoute = OnboardingChannelsRouteImport.update({
  id: '/onboarding/channels',
  path: '/onboarding/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/role',
  path: '/onboarding/role',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSourceRoute = OnboardingSourceRouteImport.update({
  id: '/onboarding/source',
  path: '/onboarding/source',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/publish': typeof PublishRoute
  '/signup': typeof SignupRoute
  '/create/editor': typeof CreateEditorRoute
  '/create/media': typeof CreateMediaRoute
  '/onboarding/channels': typeof OnboardingChannelsRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/source': typeof OnboardingSourceRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/publish': typeof PublishRoute
  '/signup': typeof SignupRoute
  '/create/editor': typeof CreateEditorRoute
  '/create/media': typeof CreateMediaRoute
  '/onboarding/channels': typeof OnboardingChannelsRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/source': typeof OnboardingSourceRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/publish': typeof PublishRoute
  '/signup': typeof SignupRoute
  '/create/editor': typeof CreateEditorRoute
  '/create/media': typeof CreateMediaRoute
  '/onboarding/channels': typeof OnboardingChannelsRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/source': typeof OnboardingSourceRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/publish'
    | '/signup'
    | '/create/editor'
    | '/create/media'
    | '/onboarding/channels'
    | '/onboarding/role'
    | '/onboarding/source'
    | '/onboarding/welcome'
    | '/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/publish'
    | '/signup'
    | '/create/editor'
    | '/create/media'
    | '/onboarding/channels'
    | '/onboarding/role'
    | '/onboarding/source'
    | '/onboarding/welcome'
    | '/create'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/dashboard'
    | '/login'
    | '/pricing'
    | '/publish'
    | '/signup'
    | '/create/editor'
    | '/create/media'
    | '/onboarding/channels'
    | '/onboarding/role'
    | '/onboarding/source'
    | '/onboarding/welcome'
    | '/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PublishRoute: typeof PublishRoute
  SignupRoute: typeof SignupRoute
  OnboardingChannelsRoute: typeof OnboardingChannelsRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  OnboardingSourceRoute: typeof OnboardingSourceRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/editor': {
      id: '/create/editor'
      path: '/editor'
      fullPath: '/create/editor'
      preLoaderRoute: typeof CreateEditorRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/media': {
      id: '/create/media'
      path: '/media'
      fullPath: '/create/media'
      preLoaderRoute: typeof CreateMediaRouteImport
      parentRoute: typeof CreateRoute
    }
    '/onboarding/channels': {
      id: '/onboarding/channels'
      path: '/onboarding/channels'
      fullPath: '/onboarding/channels'
      preLoaderRoute: typeof OnboardingChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/source': {
      id: '/onboarding/source'
      path: '/onboarding/source'
      fullPath: '/onboarding/source'
      preLoaderRoute: typeof OnboardingSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CreateRouteChildren {
  CreateEditorRoute: typeof CreateEditorRoute
  CreateMediaRoute: typeof CreateMediaRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateEditorRoute: CreateEditorRoute,
  CreateMediaRoute: CreateMediaRoute,
  CreateIndexRoute: CreateIndexRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PublishRoute: PublishRoute,
  SignupRoute: SignupRoute,
  OnboardingChannelsRoute: OnboardingChannelsRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
  OnboardingSourceRoute: OnboardingSourceRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
